apiVersion: v1
kind: ServiceAccount
metadata:
  name: rolecall-worker
  annotations:
    iam.gke.io/gcp-service-account: {{ required "serviceAccount.googleServiceAccount is required" .Values.serviceAccount.googleServiceAccount | quote }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rolecall-worker
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
